// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABCgHDlK1pyjaFIlZG6yr97c_cAN6VJ58',
    appId: '1:911994996001:web:15052c11b25d8b96502a60',
    messagingSenderId: '911994996001',
    projectId: 'hotelq-app',
    authDomain: 'hotelq-app.firebaseapp.com',
    storageBucket: 'hotelq-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIKKALXEDMTm9DsoEAtJ1aJThQB9KErRM',
    appId: '1:911994996001:android:4d226ecb0cd18e41502a60',
    messagingSenderId: '911994996001',
    projectId: 'hotelq-app',
    storageBucket: 'hotelq-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXx08e9xTNO_1eIwQY2bKtaW_3td1f25M',
    appId: '1:911994996001:ios:ddbffc33fabd0cf5502a60',
    messagingSenderId: '911994996001',
    projectId: 'hotelq-app',
    storageBucket: 'hotelq-app.appspot.com',
    iosClientId: '911994996001-5dubo7uk49mhfcejqh8438rd03m7dk9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.tsaEventq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXx08e9xTNO_1eIwQY2bKtaW_3td1f25M',
    appId: '1:911994996001:ios:ddbffc33fabd0cf5502a60',
    messagingSenderId: '911994996001',
    projectId: 'hotelq-app',
    storageBucket: 'hotelq-app.appspot.com',
    iosClientId: '911994996001-5dubo7uk49mhfcejqh8438rd03m7dk9g.apps.googleusercontent.com',
    iosBundleId: 'com.example.tsaEventq',
  );
}
